server:
  port: ${SERVER_PORT:8081}
keycloak:
  enabled: true
  auth-server-url: http://localhost:8484/auth
  realm: book_service
  resource: book_client
  bearer-only: true
  ssl-required: external
  credentials:
    secret: 7652d544-b62e-499b-b893-d8b5fba84f5f
spring:
  application.name: ${APPLICATION_NAME:book-service}
  datasource:
    url: jdbc:postgresql://localhost:5432/books_db
    username: postgres
    password: postgres
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect